build(cmake): Use FindGTest if possible
openvanilla/fcitx5-mcbopomofo pull request #95
Opened 2023-12-11 01:10 UTC by xatier

Utilize FindGTest to locate googletest if installed on the system. If googletest is not installed, fetch the specified version in src/CMakeLists.txt

Also remove redundant FetchContent blocks in subdirectories.

2023-12-11 01:14 UTC, xatier commented
@lukhnos this is the follow-up from https://github.com/openvanilla/fcitx5-mcbopomofo/pull/94

There are actually some benefits from building googletest with tarball, listed here: 
https://github.com/google/googletest/tree/main/googletest#incorporating-into-an-existing-cmake-project

Please let me know which approach you'd prefer.

2023-12-11 01:17 UTC, xatier commented
I didn't notice any difference by using the system package (https://archlinux.org/packages/extra/x86_64/gtest/) vs the tarball, they are both v1.14.0 anyway. Due to the CMake issue I noted in README, I didn't get a chance to test this on Ubuntu. Perhaps we'll see in future Ubuntu releases.

2023-12-11 15:01 UTC, lukhnos requested changes
Thank you! Just one small nit re documentation.

Re:

> There are actually some benefits from building googletest with tarball, listed here:
https://github.com/google/googletest/tree/main/googletest#incorporating-into-an-existing-cmake-project

I actually like your current approach, which uses a tagged version. Also just for my own edification, what are the benefits of using a tarball? I can't seem to find that in the gtest page above.

2023-12-14 14:29 UTC, xatier commented
@lukhnos apologies for the delayed response. I've been a bit busy recently. 

The main benefits of fetching CMake into the build directory instead of using the system installed version is that we can ensure googletest suite is built with the same tool chain as the project.

>  This has the significant advantage that the same compiler and linker settings are used between GoogleTest and the rest of your project, so issues associated with using incompatible libraries (eg debug/release), etc. are avoided. 

Another benefit is that we may use a slightly newer version of googletest (v.1.14), vs the system package (3.22.1-1ubuntu1.22.04.1).

2023-12-14 14:30 UTC, xatier commented on README.md
> +### GoogleTest
sure, let me take that part out.

2023-12-14 14:36 UTC, xatier commented
^ rebased onto upstream/master.

2023-12-15 00:08 UTC, lukhnos commented
> The main benefits of fetching CMake into the build directory instead of using the system installed version is that we can ensure googletest suite is built with the same tool chain as the project.

You mean gtest I assume. Now I see your point. At any rate, this is a relatively small and straightforward project, and as a result I feel that we should be as toolchain agnostic as possible (gcc vs clang, gtest shipped with dist vs fetched-into-build, and so on). So I think this PR is good to go.

2023-12-15 00:08 UTC, lukhnos approved these changes

2023-12-15 00:09 UTC, merged

2023-12-15 00:49 UTC, xatier commented
yeah, I meant `gtest`, morning coffee didn't kick in just yet... :coffee: